dataset:
  name: tavi_improve
  patient:
    file: data\improve\output_AK.xlsx
    columns:
      - Fallnummer
      - Vorgangsnr.
      - Name
      - Status
      - Kommentarstatus
      - Kommentar
      - RegistrierNr
      - Geburtsdatum
      - Importdatum
      - QSM_QS_STATUS
      - QS_STATUS
      - AufnQuartal
      - FACHABT
      - IntBewOrgEinheit
      - IntAufnFAB
      - IntEntlFAB
      - IntErbFAB
      - IntSonstigeFAB
      - IntStation
      - bf_IstErsteOP
      - bf_Poopvwdauer_LfdNrEingriff
      - AORTENKLAPPE
      - ENTLGRUND
      - HERZOPSONSTIGE
      - KORONARCHIRURGIE
      - LFDNREINGRIFF
      - poopvwdauer
      - abstFUErhebungsdatum
      - abstTodEntldatum
      - AKINSUFFIZIENZ
      - alter
      - ALTERJL
      - ANGINAPECTORHCH
      - ANNULUSRUPTUR
      - AORTDISSEKTION
      - AORTENKLAPPENSTENOSE
      - AORTREGURGITATION
      - ASA
      - AUFNBEFUNDBEATMUNG
      - AUFNBEFUNDDIABETES
      - AUFNBEFUNDHYPERTONIEPULMONAL
      - AUFNBEFUNDINFARKT
      - AUFNBEFUNDREANIMATION
      - AUFNBEFUNDSCHOCKKARDIOGEN
      - AUFNBEFUNDSMTRAEGER
      - AUFNNYHAERWEITERTKLAPPEN
      - AUFNRHYTHMUS
      - AVK
      - AVKAORTENANEURYSMA
      - AVKHIRNVERSORGEND
      - AVKPERIPHER
      - AVKSONSTIGE
      - BLUTUNGJL
      - Bogen
      - BSNR
      - CEREBROEREIGNIS
      - CEREBROEREIGNISDAUER
      - DEVICEEMBOLISATION
      - DEVICEFEHLPOS
      - DISSEKTION
      - DLDAUER
      - DokAbschlDat
      - DRINGLICHKEIT
      - ENTLASSSMTRAEGER
      - ENTLDIAG_1
      - ENTLDIAG_2
      - ENTLDIAG_3
      - ENTLDIAG_4
      - ENTLDIAG_5
      - ENTLDIAG_6
      - ENTLDIAG_7
      - ENTLDIAG_8
      - entlquartal
      - entlwochtag
      - FLDOSIS
      - FLDOSISUNB
      - FRAILTY
      - FUEHRENDEROPS
      - gebjahr
      - GEFKOMPLIKAT
      - GEFRUPTUR
      - GEFVERSCHLNR
      - GESCHLECHT
      - GRAFTSANZAHL
      - GRAFTSITALINKS
      - GRAFTSSONSTIGE
      - HAEMATOMJL
      - HAUPTSTAMMSTENOSE
      - HIRNEMBOLIE
      - HOCHRISIKO
      - IKNRKH
      - INFEKTIONAKUTHCH_1
      - INFEKTIONAKUTHCH_2
      - INFEKTIONAKUTHCH_3
      - INOTROPEIV
      - IOPKOMPJN
      - ISCHAEMIEJL
      - KMMENGE
      - KOERPERGEWICHT
      - KOERPERGEWICHTNB
      - KOERPERGROESSE
      - KOERPERGROESSENB
      - KONVERSION
      - KOROANGBEFUND
      - KREATININWERTMGDL
      - KREATININWERTMOLL
      - KREISLAUFUNTERSTUETZUNG
      - LUNGENERKRANKUNGEN
      - LVDEKOMPENSATION
      - LVEF
      - MALIGNOM
      - MEDIASTINITIS
      - Modul
      - NEUROLOGISCHEERKRANKUNGEN
      - NITRATEIV
      - OPDAUER
      - opquartal
      - OPSCHLUESSEL_1
      - OPSCHLUESSEL_2
      - OPSCHLUESSEL_3
      - OPSCHLUESSEL_4
      - OPSCHLUESSEL_5
      - OPSCHLUESSEL_6
      - OPSCHLUESSEL_7
      - OPSCHLUESSEL_8
      - OPSCHLUESSEL_9
      - OPSCHLUESSEL_10
      - OPSCHLUESSEL_11
      - OPSCHLUESSEL_12
      - OPSCHLUESSEL_13
      - OPSCHLUESSEL_14
      - OPSCHLUESSEL_15
      - OPSCHLUESSEL_16
      - OPSCHLUESSEL_17
      - OPSCHLUESSEL_18
      - OPSCHLUESSEL_19
      - OPSCHLUESSEL_20
      - PATWUNSCH
      - PCIHCH
      - PERIKARDTAMPO
      - PORZAORTA
      - PRAENIEREERSATZTH
      - PRAEOPCDC
      - PROGLIMZWEITERKR
      - quartalFUErhebungsdatum
      - quartalTodesdatum
      - RANKINENTL
      - RANKINSCHLAGANFALL
      - RHYTHMUSSTOERUNG
      - SONSTIGE
      - Standort
      - STATUS30TAGEPOSTOP
      - Storno
      - TROPONIN
      - VASKKOMPLIKAT
      - VersionNr
      - VOROPANZAHL
      - vwDauer
      - ZUGANGHCH
      - TABLENAME
      - bf_AKLScore2
      - bf_BMI
      - bf_KreatininPraeMGDL
      - bf_OPistHCHAortKath
      - kreatininwertmgdl
      - kreatininwertmoll
      - bf_euroSCORE_I
      - Alter
      - bf_IntraprozeduraleKomplikation
      - bf_ArterielleKomplikation
      - bf_StatusBekannt30T
      - bf_TodInnerhalb30T
      - poopVwDauer
      - bf_AKL_KATH_Score
      - ENTLDIAG_9
      - ENTLDIAG_10
      - ENTLDIAG_11
      - ENTLDIAG_12
      - ENTLDIAG_13
      - ENTLDIAG_14
      - ENTLDIAG_15
      - ENTLDIAG_16
      - ENTLDIAG_17
      - ENTLDIAG_18
      - ENTLDIAG_19
      - ENTLDIAG_20
      - ENTLDIAG_21
      - ENTLDIAG_22
      - ENTLDIAG_23
      - ENTLDIAG_24
      - ENTLDIAG_25
      - ENTLDIAG_26
      - ENTLDIAG_27
      - ENTLDIAG_28
      - ENTLDIAG_29
      - ENTLDIAG_30
      - STANDORTOPS
      - EntlQuartal
      - bf_OPistKCHK_AKKath
      - MITREING
      - PULMKL
      - SPEZJAHR
      - SYSTPULMDR
      - TRIKUSP
      - WEITEINGR
      - abstOPzerebov
      - ACEHEMMER
      - ALDOSTANTAGONIST
      - ANEURYSMA
      - AVFISTEL
      - BESCHW
      - BETABLOCKER
      - BLUTSCHW
      - BLUTSCHWPOST
      - DIURETIKA
      - ENDOKARD
      - ERGEBNIS
      - EROA
      - EROANV
      - EXITUS
      - FIBRVERD
      - FLAILLEAFLET
      - HAEMATBLUTUN
      - HERZNG
      - HERZOHRV
      - IdBogenFeldMutter
      - INFARKTPOSTOP
      - INSUFF
      - kasseiknr2Stellen
      - KEINKM
      - KOAPTLUECK
      - KOMMIS
      - KOMPLINFEKT
      - KOMPLMECHJN
      - LECKAGE
      - LFDNRAORT
      - LFDNRKC
      - LFDNRMKE
      - LOWCARD
      - LOWCARDTH
      - LVEFUNBEKANNT
      - LVESD
      - LVESDNV
      - MEDIKTH
      - MKOEFFN
      - MKOEFFNNV
      - MORPH
      - NIERENVERS
      - PCIDATUM
      - PERIKARDTAMPOST
      - REANIMPOSTOP
      - REEING
      - REVASK
      - RISKBEGL
      - RISKEMBOLIE
      - RISKHAEMDYN
      - RUPTHERZH
      - RUPTPAPIL
      - RVOL
      - RVOLNV
      - SEGELPROLAPS
      - SITZPROTH
      - SONSTMEDIK
      - standortID
      - standortIDops
      - STERNUM
      - SYSTPULMDRNV
      - THROMB
      - VEGET
      - VENAC
      - VENACNV
      - VERK
      - versichertenidgkv
      - versichertenstatusgkv
      - VHABL
      - VHFLIMM
      - VHSEPT
      - VITIUM
      - VorgangsnrGuid
      - WECHSEING
      - WEITEINGRSONST
      - ZUGKOMPLSONST
      - INTERPCI
      - KONVEREINGRIFF
      - OPDATUM
      - NICHTSPEZENTLGRUND
      - ZUGANGKC
      - ZUGANGMKE
    filters: []
    processor: null
